Repository jupyter/jupyter_events, pull requests merged in 2022-09, with the labels that each got.

#23 Add pytest plugin for testing events in other libraries
  jupyter_events/pytest_plugin.py
  pyproject.toml
  tests/conftest.py
  tests/test_listeners.py
  tests/test_modifiers.py
Labels: enhancement

#25 Set version floor on jsonchema
  pyproject.toml
Labels: maintenance

#28 use safe loaders and dumpers in yaml lib
  jupyter_events/yaml.py
Labels: bug

#29 specify utf-8 encoding for loading/dumping yaml
  jupyter_events/yaml.py
Labels: bug

#30 Add CLI tests, return codes, version
  .github/workflows/python-tests.yml
  docs/user_guide/defining-schema.md
  jupyter_events/__init__.py
  jupyter_events/cli.py
  jupyter_events/yaml.py
  pyproject.toml
  tests/test_cli.py
Labels: maintenance

#31 add jsonschema[format-nongpl], core event schema
  .github/workflows/python-tests.yml
  docs/demo/demo-notebook.ipynb
  docs/user_guide/application.md
  docs/user_guide/defining-schema.md
  docs/user_guide/event-schemas.md
  docs/user_guide/first-event.md
  jupyter_events/__init__.py
  jupyter_events/logger.py
  jupyter_events/schema.py
  jupyter_events/schemas/event-core-schema.yml
  jupyter_events/schemas/event-metaschema.yml
  jupyter_events/validators.py
  pyproject.toml
  tests/schemas/bad/bad-id.yaml
  tests/test_logger.py
  tests/test_schema.py
Labels: maintenance

#32 Automated Changelog Entry for 0.5.0 on main
  CHANGELOG.md
Labels: documentation

#33 Clean up pyproject and ci
  .github/workflows/python-tests.yml
  jupyter_events/_version.py
  pyproject.toml
Labels: maintenance
