Repository jupyter/jupyter_events, pull requests merged in 2022-08, with the labels that each got.

#5 Automated Changelog Entry for 0.2.0 on main
  CHANGELOG.md
Labels: documentation

#6 Add JupyterLite example to the documentation
  docs/demo/demo-notebook.ipynb
  docs/requirements.txt
  docs/user_guide/first-event.md
Labels: documentation

#14 Fix check_release build
  .github/workflows/check-release.yml
  docs/user_guide/event-schemas.md
Labels: maintenance

#15 Reading strings as file path is unsafe
  jupyter_events/schema.py
Labels: bug

#12 Add a "modifiers" hook to allow extension authors to mutate/redact event data
  docs/user_guide/application.md
  docs/user_guide/first-event.md
  docs/user_guide/index.md
  docs/user_guide/modifiers.md
  jupyter_events/__init__.py
  jupyter_events/logger.py
  jupyter_events/schema_registry.py
  tests/schemas/good/user.yaml
  tests/test_logger.py
  tests/test_modifiers.py
Labels: enhancement

#16 Remove (duplicate) version argument from API
  docs/demo/demo-notebook.ipynb
  docs/user_guide/application.md
  docs/user_guide/first-event.md
  docs/user_guide/modifiers.md
  jupyter_events/logger.py
  jupyter_events/schema.py
  jupyter_events/schema_registry.py
  tests/test_logger.py
  tests/test_modifiers.py
Labels: enhancement

#10 Add Listeners API
  docs/demo/demo-notebook.ipynb
  docs/user_guide/index.md
  docs/user_guide/listeners.md
  jupyter_events/logger.py
  jupyter_events/schema_registry.py
  tests/test_listeners.py
Labels: enhancement

#17 Automated Changelog Entry for 0.3.0 on main
  CHANGELOG.md
Labels: documentation

#18 Add method to remove modifier
  jupyter_events/logger.py
  jupyter_events/schema_registry.py
  tests/test_listeners.py
Labels: enhancement

#19 Fix minor bugs in Listeners API
  jupyter_events/logger.py
Labels: bug

#9 Add a simple CLI tool for validating event schemas
  docs/user_guide/defining-schema.md
  jupyter_events/cli.py
  jupyter_events/logger.py
  jupyter_events/schema.py
  jupyter_events/validators.py
  pyproject.toml
Labels: enhancement

#20 Automated Changelog Entry for 0.4.0 on main
  CHANGELOG.md
Labels: documentation

#21 docs: wrap shell command in quotes
  docs/user_guide/defining-schema.md
Labels: documentation
