Repository jupyter/jupyter_events, pull requests merged in 2023-04, with the labels that each got.

#72 allow a 'message' field in an event schema
  jupyter_events/logger.py
  jupyter_events/schema.py
  tests/test_logger.py
Labels: enhancement

#73 Use local coverage
  .github/workflows/python-tests.yml
  README.md
  codecov.yml
  pyproject.toml
Labels: maintenance

#74 Improve usability of jp_read_emitted_events fixture
  jupyter_events/logger.py
  jupyter_events/pytest_plugin.py
Labels: bug
