Repository jupyter/jupyter_events, pull requests merged in 2024-12, with the labels that each got.

#102 Fix typo
  docs/user_guide/defining-schema.md
  docs/user_guide/first-event.md
Labels: documentation

#106 test on 3.13
  .github/workflows/python-tests.yml
Labels: maintenance

#104 Switch schema `version` type to `str`
  docs/demo/demo-notebook.ipynb
  docs/user_guide/application.md
  docs/user_guide/defining-schema.md
  docs/user_guide/event-schemas.md
  docs/user_guide/first-event.md
  jupyter_events/schemas/event-core-schema.yml
  jupyter_events/schemas/event-metaschema.yml
  jupyter_events/schemas/property-metaschema.yml
  jupyter_events/utils.py
  jupyter_events/validators.py
  pyproject.toml
  tests/schemas/bad/bad-id.yaml
  tests/schemas/bad/nested-reserved-property.yaml
  tests/schemas/good/array.yaml
  tests/schemas/good/basic.json
  tests/schemas/good/basic.yaml
  tests/schemas/good/nested-array.yaml
  tests/schemas/good/user.yaml
  tests/test_logger.py
Labels: bug

#107 Fix typo and remove double check.
  .github/workflows/python-tests.yml
  docs/user_guide/event-schemas.md
Labels: maintenance

#109 declare dependency on packaging
  pyproject.toml
Labels: maintenance, dependencies
